### ISSUE TITLE
OSError on blit function, when using lv.DISPLAY_RENDER_MODE.FULL

### ISSUE THREAD

**Issue by sam0910** [bdbarnett/mpdisplay#2]
Greetings!

Thank you so much for the driver!
I could finally using latest lvgl on micropython :)

when lv.DISPLAY_RENDER_MODE.FULL(using large buffer), 
there is OSError on blit function(busdisplay.py)

Could you help?
I am using esp32-pico-v3-02(flash 8M. spiram 2M) , gc9a01, 16bit
```
#lv_driver_framework.py, on line 72
print(len(self._frame_buffer1), ">=", display.width * display.height * self._color_size)
115200 >= 115200

Traceback (most recent call last):
  File "lv_utils.py", line 142, in task_handler
  File "lv_driver_framework.py", line 115, in _flush_cb
  File "busdisplay.py", line 255, in blit
OSError: 257(esp_lcd_panel_io_tx_color)
```

**Comment by sam0910** [comment]
I think esp32 doesn't have enough buffer of (240*240*2) in CAP_DMA|CAP_INTERNAL
lv_driver_framwork.py allocates (240*240*2) bytes in SPIRAM.
